name: Deploy website to Production
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy using PowerShell and SCP
      - name: Deploy to server using SCP
        run: |
          $ServerHost = "${{ vars.SERVER_HOST }}"
          $ServerUser = "${{ vars.SERVER_USER }}"
          $ServerPath = "${{ vars.SERVER_PATH }}"
          $KeyPath = "C:\Users\flori\.ssh\id_rsa"
          $SourcePath = "${{ github.workspace }}\*"
          $RemotePath = "$($ServerUser)@$($ServerHost):$($ServerPath)"
          scp -i $KeyPath -r $SourcePath $RemotePath
        shell: powershell
